### ISSUE TITLE
Access Denied when trying to download linux version

### ISSUE THREAD

**Issue by ajunge** [vinumeris/lighthouse#103]
This link is not working for me:

https://s3-eu-west-1.amazonaws.com/vinumeris/lighthouse/lighthouse.deb

**Comment by ajunge** [comment]
Windows and Mac version also with problems:

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>56AF0767EBE578F1</RequestId>
  <HostId>pyW7Ay2+a0fcG4+KkIekfr8gHxOTT0+gncZUscmBCGKVOfuCBKDe7EFv6IQSsVQT8orE1mJKjpM=</HostId>
</Error>

**Comment by mikehearn** [comment]
Where did you get the link from? That one is very old.

Alpha is about to become beta so I'm not intending to take on more testers at the moment ... the last round of testing feedback was positive. But if you want to try it anyway, try lighthouse-6.deb instead of lighthouse.deb
