### ISSUE TITLE
Binary throws SIGSEGV (deb)

### ISSUE THREAD

**Issue by slush0** [vinumeris/lighthouse#119]
Officially distributed deb randomly crashes during startup on SIGSEGV.

*** Error in `./lighthouse': double free or corruption (out): 0x00007f3a38000c80 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x80996)[0x7f3acd495996]
/lib/x86_64-linux-gnu/libc.so.6(fclose+0x14d)[0x7f3acd4839bd]
/lib/x86_64-linux-gnu/libnss_files.so.2(_nss_files_gethostbyname4_r+0x30a)[0x7f3acba4082a]
/lib/x86_64-linux-gnu/libc.so.6(+0xccae0)[0x7f3acd4e1ae0]
/lib/x86_64-linux-gnu/libc.so.6(getaddrinfo+0xf4)[0x7f3acd4e5914]
/opt/lighthouse/runtime/jre/lib/amd64/libnet.so(Java_java_net_Inet6AddressImpl_lookupAllHostAddr+0x89)[0x7f3ab8603439]
[0x7f3abc1f16d4]
======= Memory map: ========
00400000-00406000 r-xp 00000000 fc:01 6111871                            /opt/lighthouse/lighthouse
00605000-00606000 r--p 00005000 fc:01 6111871                            /opt/lighthouse/lighthouse
00606000-00607000 rw-p 00006000 fc:01 6111871                            /opt/lighthouse/lighthouse
00607000-00609000 rw-p 00000000 00:00 0 
02276000-02678000 rw-p 00000000 00:00 0                                  [heap]
87e00000-8c200000 rw-p 00000000 00:00 0 
8c200000-d7f80000 ---p 00000000 00:00 0 
d7f80000-dc680000 rw-p 00000000 00:00 0 
dc680000-100000000 ---p 00000000 00:00 0 
100000000-100380000 rw-p 00000000 00:00 0 
100380000-140000000 ---p 00000000 00:00 0 
7f3a38000000-7f3a38021000 rw-p 00000000 00:00 0 
7f3a38021000-7f3a3c000000 ---p 00000000 00:00 0 
7f3a40000000-7f3a40021000 rw-p 00000000 00:00 0 
7f3a40021000-7f3a44000000 ---p 00000000 00:00 0 
7f3a44000000-7f3a44021000 rw-p 00000000 00:00 0 
7f3a44021000-7f3a48000000 ---p 00000000 00:00 0 
7f3a48000000-7f3a48021000 rw-p 00000000 00:00 0 
7f3a48021000-7f3a4c000000 ---p 00000000 00:00 0 
7f3a4c000000-7f3a4c023000 rw-p 00000000 00:00 0 
7f3a4c023000-7f3a50000000 ---p 00000000 00:00 0 
7f3a50000000-7f3a50021000 rw-p 00000000 00:00 0 
7f3a50021000-7f3a54000000 ---p 00000000 00:00 0 
7f3a54000000-7f3a54110000 rw-p 00000000 00:00 0 
7f3a54110000-7f3a58000000 ---p 00000000 00:00 0 
7f3a58000000-7f3a58021000 rw-p 00000000 00:00 0 
7f3a58021000-7f3a5c000000 ---p 00000000 00:00 0 
7f3a5c000000-7f3a5c025000 rw-p 00000000 00:00 0 
7f3a5c025000-7f3a60000000 ---p 00000000 00:00 0 
7f3a60000000-7f3a6069e000 rw-p 00000000 00:00 0 
7f3a6069e000-7f3a64000000 ---p 00000000 00:00 0 
7f3a64000000-7f3a64021000 rw-p 00000000 00:00 0 
7f3a64021000-7f3a68000000 ---p 00000000 00:00 0 
7f3a68000000-7f3a68021000 rw-p 00000000 00:00 0 
7f3a68021000-7f3a6c000000 ---p 00000000 00:00 0 
7f3a6cd8a000-7f3a6ce8b000 rw-p 00000000 00:00 0 
7f3a6ce8b000-7f3a6ce8e000 ---p 00000000 00:00 0 
7f3a6ce8e000-7f3a6cf8c000 rw-p 00000000 00:00 0                          [stack:9250]
7f3a6cf8c000-7f3a6cf8f000 ---p 00000000 00:00 0 
7f3a6cf8f000-7f3a6d0cd000 rw-p 00000000 00:00 0                          [stack:9249]
7f3a6d0cd000-7f3a6d28d000 ---p 00000000 00:00 0 
7f3a6d28d000-7f3a6d290000 ---p 00000000 00:00 0 
7f3a6d290000-7f3a6d38e000 rw-p 00000000 00:00 0                          [stack:9248]
7f3a6d38e000-7f3a6d391000 ---p 00000000 00:00 0 
7f3a6d391000-7f3a6d48f000 rw-p 00000000 00:00 0                          [stack:9247]
7f3a6d48f000-7f3a6d544000 r--p 00000000 fc:01 12454074                   /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
7f3a6d544000-7f3a6d57e000 r--p 00000000 fc:01 6190351                    /opt/lighthouse/runtime/jre/lib/fonts/LucidaTypewriterBold.ttf
7f3a6d57e000-7f3a6d5d3000 r--p 00000000 fc:01 6190346                    /opt/lighthouse/runtime/jre/lib/fonts/LucidaBrightRegular.ttf
7f3a6d5d3000-7f3a6d5e6000 r--p 00000000 fc:01 6190352                    /opt/lighthouse/runtime/jre/lib/fonts/LucidaBrightDemiBold.ttf
7f3a6d5e6000-7f3a6d5f9000 r--p 00000000 fc:01 6190348                    /opt/lighthouse/runtime/jre/lib/fonts/LucidaBrightDemiItalic.ttf
7f3a6d5f9000-7f3a6d60d000 r--p 00000000 fc:01 6190347                    /opt/lighthouse/runtime/jre/lib/fonts/LucidaBrightItalic.ttf
7f3a6d60d000-7f3a6d610000 ---p 00000000 00:00 0 
7f3a6d610000-7f3a6d70e000 rw-p 00000000 00:00 0                          [stack:9245]
7f3a6d70e000-7f3a6d7b9000 r--p 00000000 fc:01 6190350                    /opt/lighthouse/runtime/jre/lib/fonts/LucidaSansRegular.ttf
7f3a6d7b9000-7f3a6d7bc000 ---p 00000000 00:00 0 
7f3a6d7bc000-7f3a6d8ba000 rw-p 00000000 00:00 0                          [stack:9244]
7f3a6d8ba000-7f3a6d957000 rw-s 00000000 fc:01 6308762                    /home/marekp/.local/share/Lighthouse/production/Lighthouse.spvchain
7f3a6d957000-7f3a6d9a5000 r--p 00000000 fc:01 6190345                    /opt/lighthouse/runtime/jre/lib/fonts/LucidaSansDemiBold.ttf
7f3a6d9a5000-7f3a6d9e1000 r--p 00000000 fc:01 6190344                    /opt/lighthouse/runtime/jre/lib/fonts/LucidaTypewriterRegular.ttf
7f3a6d9e1000-7f3a6dbe1000 rw-p 00000000 00:00 0 
7f3a6dbe1000-7f3a6dc13000 r-xp 00000000 fc:01 6190376                    /opt/lighthouse/runtime/jre/lib/amd64/libsunec.so
7f3a6dc13000-7f3a6de12000 ---p 00032000 fc:01 6190376                    /opt/lighthouse/runtime/jre/lib/amd64/libsunec.so
7f3a6de12000-7f3a6de18000 rw-p 00031000 fc:01 6190376                    /opt/lighthouse/runtime/jre/lib/amd64/libsunec.so
7f3a6de18000-7f3a6e028000 rw-p 00000000 00:00 0 
7f3a6e028000-7f3a6e02b000 ---p 00000000 00:00 0 
7f3a6e02b000-7f3a6e329000 rw-p 00000000 00:00 0                          [stack:9246]
7f3a6e329000-7f3a6e32c000 ---p 00000000 00:00 0 
7f3a6e32c000-7f3a6e42a000 rw-p 00000000 00:00 0                          [stack:9241]
7f3a6e42a000-7f3a6e430000 r-xp 00000000 fc:01 2101119                    /lib/x86_64-linux-gnu/libnss_dns-2.17.so
7f3a6e430000-7f3a6e62f000 ---p 00006000 fc:01 2101119                    /lib/x86_64-linux-gnu/libnss_dns-2.17.so
7f3a6e62f000-7f3a6e630000 r--p 00005000 fc:01 2101119                    /lib/x86_64-linux-gnu/libnss_dns-2.17.so
7f3a6e630000-7f3a6e631000 rw-p 00006000 fc:01 2101119                    /lib/x86_64-linux-gnu/libnss_dns-2.17.so
7f3a6e631000-7f3a6e633000 r-xp 00000000 fc:01 2097192                    /lib/libnss_mdns4_minimal.so.2
7f3a6e633000-7f3a6e832000 ---p 00002000 fc:01 2097192                    /lib/libnss_mdns4_minimal.so.2
7f3a6e832000-7f3a6e833000 r--p 00001000 fc:01 2097192                    /lib/libnss_mdns4_minimal.so.2
7f3a6e833000-7f3a6e834000 rw-p 00002000 fc:01 2097192                    /lib/libnss_mdns4_minimal.so.2
7f3a6e834000-7f3a6e837000 ---p 00000000 00:00 0 
7f3a6e837000-7f3a6e935000 rw-p 00000000 00:00 0                          [stack:9240]
7f3a6e935000-7f3a6ebb5000 rw-s 10bb54000 00:05 1136                      /dev/dri/card0
7f3a6ebb5000-7f3a6edb5000 rw-p 00000000 00:00 0 
7f3a6edb5000-7f3a6edec000 r-xp 00000000 fc:01 6190409                    /opt/lighthouse/runtime/jre/lib/amd64/libjavafx_iio.so
7f3a6edec000-7f3a6efeb000 ---p 0#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Aborted

**Comment by mikehearn** [comment]
This looks very similar to a previously reported issue on Linux that affected Bitcoin Authenticator. If you remove/rename the /etc/hosts file temporarily does it go away?

I never got a chance to fully debug it, but it looks a lot like a thread safety problem in the glibc file parser for NSS related files i.e. a bug in the Linux userland. I suspect something about the way we're doing DNS lookups in parallel on different threads tickles the problem.

If temporarily removing /etc/hosts fixes it, then I'll take a look at adding some locking at the app level to work around the glibc bug.

**Comment by mikehearn** [comment]
Discussion of this bug in a different context:

https://groups.google.com/forum/#!searchin/bitcoinj/glibc/bitcoinj/r5S3jMQc0nI/FGNxBhzSHMMJ

**Comment by slush0** [comment]
Good catch! After renaming /etc/hosts problem disappeared. 20 startups, no crash.

By the way, congrats with the project, we're internally testing it in SatoshiLabs right now :-).

**Comment by mikehearn** [comment]
Sweet! Thanks for the testing :)

OK, I previously thought this would only be triggered when Tor is in use (because that involves doing tons of DNS lookups in parallel), but I see now this is wrong and any bitcoinj based app can trigger it.

I will investigate solutions. An LD_PRELOAD that serialises all calls to gethostbyname is probably the simplest quick hack, but it would be fiddly to deploy as the deb packages are auto-generated by a tool. Adding locking in bitcoinj would probably work but wouldn't fix things for Tor users. Hmm, will have a think.

**Comment by mikehearn** [comment]
Hey slush, 

I pushed an update with an experimental workaround. It just serialises the DNS seed lookups. I don't know if it fixes the problem because I cannot reproduce it on any of my Linux systems. If you start the app and let it update itself, then restore your /etc/hosts file and try again, that'd be helpful. If it still segfaults then I guess the issue can be aggravated by other DNS lookups being done during startup too.

**Comment by ajweiss** [comment]
I can confirm that on my Ubuntu 14.04.01 system, this crash happens frequently on startup and can be avoided by fooling with /etc/hosts.  I've also noted that either the pull-down of the update or the initialization of the settings/data directory causes the problem to disappear.  Did you push your fix into the update that is pulled down?  If so, you may wish to consider pushing that to the homepage download link, as the current broken OOBE on Linux is no good.

Also, the newer version seems to want to always take over my whole screen, it may be a matter of taste but I think that's kinda rude!

**Comment by mikehearn** [comment]
Yes, the workaround is a part of the latest update. It's good to hear that this fixes things! Already got the feedback about maximization not being the right default and memorisation of the last size/position is in git master and will go out with the next update. Yep, I need to rebuild the packages on the download page - it's on the TODO list. I'll try and get to it this week or next.

Thanks for letting me know!

**Comment by mikehearn** [comment]
The binaries on the website have been refreshed so I hope nobody will encounter this anymore.
