### ISSUE TITLE
Changing target address after a project is created doesn't work

### ISSUE THREAD

**Issue by mikehearn** [vinumeris/lighthouse#124]
Reported by miketay on IRC. This should be allowed if there are no pledges.

**Comment by miketay** [comment]
Also related, when user clicks on "Create new project", an address is automatically generated.  If the user edits that address, but it's not a valid Bitcoin address, it doesn't warn or stop the user but continues to use the auto-generated one.

**Comment by mikehearn** [comment]
It should turn the edit red if it's not a valid bitcoin address. I'll try and reproduce this.

**Comment by mikehearn** [comment]
I was able to edit the address in a test project I just created. Are you replacing the original file? Changing the title? If you save the edited project to a new file, it's seen as a brand new project, effectively duplicating it.

**Comment by mikehearn** [comment]
Update pushed
