### ISSUE TITLE
Freezes when I click on my address

### ISSUE THREAD

**Issue by petertodd** [vinumeris/lighthouse#127]
As the title says, when I click on my address in the main page the entire app freezes; the UI doesn't redraw. CPU usage is zero.

Running Ubuntu 14.04 w/ xmonad as my window manager.

**Comment by petertodd** [comment]
Oh, and for more info, this happened after I first used the app w/o a deposit of funds, and is still happening with a deposit of funds. I tried sending some funds to the address, and at 1 conf the balance amount isn't changing.

**Comment by mikehearn** [comment]
This was reported once before and was a Linux specific issue with gnome/xdg-open. It's trying to open a bitcoin: URI and something is going wrong, probably there is no handler and the JRE code isn't dealing with that properly.

**Comment by petertodd** [comment]
Ah ok.

So there's no way to get a wallet transactions list in Lighthouse yet? That's what I assumed clicking on an address did actually.

**Comment by mikehearn** [comment]
No, there's no way to see a transaction list and I don't currently plan on adding any. The wallet functionality is minimal on purpose, it's not meant to be used as a regular daily spending wallet. That's why the only way to take money out is empty the whole thing.
