### ISSUE TITLE
can't pledge

### ISSUE THREAD

**Issue by rolandkofler** [vinumeris/lighthouse#141]
While the wallet shows my money I can't pledge bitsquale because the button is inactive
![image](https://cloud.githubusercontent.com/assets/979444/5887390/729c4f0e-a3cd-11e4-9539-b9905812b94b.png)
Hint: I needed to rename /etc/hosts according to Mikes instructions to run it on Ubuntu 14.04

**Comment by mikehearn** [comment]
It thinks you don't have enough money. What was your balance at the time?

**Comment by mikehearn** [comment]
... or that amount was larger than the amount of money remaining to be raised.

**Comment by rolandkofler** [comment]
yes not enough money
