### ISSUE TITLE
Error message on startup - Online Update failed

### ISSUE THREAD

**Issue by MarcSte** [vinumeris/lighthouse#147]
"An error was encountered whilst attempting to download or apply an online update: com.vinumeris.updatefx.Updater$Ex$BadUpdateHash"

Windows 8.1

**Comment by mikehearn** [comment]
Hey Marc,

Were you an alpha tester? Could you dig out your c:\Users\marcste\AppData\Roaming\Lighthouse\23.jar and send it to me please? When I've tested the app from the website the update process has worked OK so I'm not sure what is being different here ....

**Comment by MarcSte** [comment]
Hi Mike,

not sure if you got my email. I uploaded the file here: https://mega.co.nz/#!FUhnjAqS!X8M6lcSJmUMDXzi5obr1BcM49o_t5H3McYaDwtaf0FM

I haven't been an alpha tester. The app updated fine before. Don't know what happened.

**Comment by MarcSte** [comment]
Simple reinstall didn't help. After I deleted the Lighthouse folder from */AppData/Roaming everything's working fine again.

**Comment by mikehearn** [comment]
Be careful doing that! This directory contains your wallet! Unless you wrote down your wallet words, blowing away that directory can cause destruction of money.

I'll take a look at the jar to see what happened soon. Most other people seem to have updated without issue.

**Comment by mikehearn** [comment]
I'm not sure exactly how this happened, but your JAR appears to have been compiled a few seconds before the released one. I wonder if I overwrote the update shortly after upload and have forgotten. At least, nobody else has reported this, so I think I will close this and be extra careful to never replace updates in future. Thanks for the report.
