### ISSUE TITLE
Pledging more than once is not allowed

### ISSUE THREAD

**Issue by kenCode-de** [vinumeris/lighthouse#150]
Would be nice if that was allowed :)

**Comment by mikehearn** [comment]
You can just revoke your previous pledge, and then pledge more.

**Comment by kenCode-de** [comment]
Oh ok, will let them know that thanx Mike :)


<sig>
ken Code
COO, http://kenCode.de
Crypto + IoT + Distrib Computing + Meshnet: #ePlug
#kenCode +kenCode @kenCode_de
München, Deutschland
</sig>
