### ISSUE TITLE
Revoking my pledge works, but the Revoke button remains in place

### ISSUE THREAD

**Issue by johndevor** [vinumeris/lighthouse#152]
The Revoke button should revert to its "Make pledge" state

**Comment by johndevor** [comment]
Mac OS X latest

On the Bitsquare lighthouse project

**Comment by johndevor** [comment]
During the first time I try to revoke, the progress bar gets stuck here: http://d.pr/i/18DkQ

**Comment by johndevor** [comment]
Revoking for a second time and the progress bar goes back and forth normally without getting frozen

**Comment by johndevor** [comment]
Still trying to revoke the pledge from the project, came across this crash: http://d.pr/n/105pV

**Comment by mikehearn** [comment]
The crash is saying the revoke already took place. Can you send me the log.txt file in your app's data directory? It sounds like the initial revoke didn't see the transaction propagate across the Bitcoin network even though it did actually work. P2P networks are great fun, aren't they ....

**Comment by johndevor** [comment]
Sent it your way. Emailed it cause I'm not sure if there's anything sensitive in it

**Comment by mikehearn** [comment]
I've tweaked how revocation broadcast tracking works since this bug report was filed so it should be more robust now ... thus I'm going to tentatively close this report. If we see it again I'll reopen.
