### ISSUE TITLE
Error: Read timed out

### ISSUE THREAD

**Issue by kenCode-de** [vinumeris/lighthouse#153]
The Pledges to my project stopped showing up. Did I do something wrong? 
Thanx in advance guys :)
  -ken

**Comment by mikehearn** [comment]
Which server are you using?

**Comment by kenCode-de** [comment]
I think I used that secondary server with Joe, since you were gone that weekend I could not get the project file onto the vinumeris server. the domain started with the letter T i think, can't remember the exact name.

**Comment by mikehearn** [comment]
OK, then we need to ask @JoeSchmid about it.

**Comment by kenCode-de** [comment]
Let me know if you need anything from me then, I'm here. My skype too is: kenCode_de

**Comment by kenCode-de** [comment]
I'm kinda new to github so please ask him if ya could for me, thanx Mike :)

**Comment by kenCode-de** [comment]
Steps to reproduce: Open Lighthouse on linux mint, sync with bitcoin network works fine, other projects I have imported load just fine and their pledges are viewable. click on my project though, and that error message above appears and the pledges are not viewable.

**Comment by joeschmid** [comment]
Hi Ken, it should be fixed now. I needed to restart the Lighthouse server. It's been quite stable, but in this case it seemed to stop responding to HTTPS requests. (It seemed to be responding to bitcoin network messages fine though.)

**Comment by kenCode-de** [comment]
Yep, everything works perfectly again. Did I mention you guys are gods? Thanx again Joe and Mike :) I'll send it to you in a few days, but fyi: https://twitter.com/kenCode_de/status/565186437281099776
