### ISSUE TITLE
Build instructions in README

### ISSUE THREAD

**Issue by rapodaca** [vinumeris/lighthouse#154]
The README says:

> If you're a developer, build instructions are at the end of this README.

But there are no build instructions. I don't use Maven much, so the procedure wan't obvious. I was able to figure it out (I think), and wrote up something that could be included in the README:

# building from source

Building Lighthouse from source requires the [Maven](http://maven.apache.org/) build tool and the [bitcoinj](http://bitcoinj.github.io/) library.

The latest version of bitcoinj should be [installed from source](https://github.com/bitcoinj/bitcoinj):

```
$ git clone https://github.com/bitcoinj/bitcoinj
$ cd bitcoinj
$ mvn clean install
```

Compile Lighthouse with:

```
$ git clone https://github.com/vinumeris/lighthouse
$ cd lighthouse
$ mvn clean package
```

Run Lighthouse with:

```
$ java -jar client/target/shaded.jar
```

I'm willing to revise/submit PR if needed.

**Comment by mikehearn** [comment]
Thanks!
