### ISSUE TITLE
don't quit the app when closing the window on OSX

### ISSUE THREAD

**Issue by jsuder** [vinumeris/lighthouse#156]
Right now the app quits completely when the main window is closed with Cmd+W or by pressing the red X button. This is not standard behavior on OSX - most apps simply close the main/document window, and only quit when you press Cmd+Q. There are exceptions, but they're usually lightweight system apps that start and close really quickly. Quitting on close is confusing and requires you to actively remember not to do it (and hide the window e.g. with Cmd+H), working against your muscle memory.

I was hoping this would be something obvious that I could fix myself, but it looks like this is standard JavaFX behavior and fixing this probably requires setting some event handlers in the right places, and I gave up after my attempt with setOnCloseRequest failed (adding that disabled window closing, but also Cmd+Q, which seems to be handled in the same handler...).

**Comment by mikehearn** [comment]
Lots of Mac apps quit on close. For example System Preferences does this. So does TextEdit. These aren't exceptions, they're the default apps that set the expectations for the rest of the platform.

IMO MacOS is just hosed in this regard. Apple screwed up big time. The old MacOS behaviour makes no sense, isn't what Windows or Linux do, and results in users leaving apps lying around in memory that they've forgotten about (out of sight, out of mind). So not surprisingly Apple tried to move away from it. But old apps still hang on to the old behaviour so it gets confusing.

I don't see any benefits to giving Lighthouse the old broken behaviour. It starts in a second or two on my box unless I have tons of projects loaded, that's fast enough.

**Comment by jsuder** [comment]
Well, as a Mac user since 2008 I must say I disagree, but I don't want to argue about it, it's your app so do it your way :)

About that speed though, on my MBA it takes about 2-3 seconds until the "splash screen" and another 4-5 seconds until the project list appears (with 4 projects). It's not a brand new device, but I do all my paid work on it so it's not too slow yet either.

**Comment by mikehearn** [comment]
Hmm, that's a lot slower than what I see. What kind of CPU and disk does the MacBook Air have? Could you send me a log.txt?

One issue I can see is that if the main window is closed, it doesn't make sense to just hide it because the user might not want the app back for a long time. So I'd want to deallocate all the UI resources to give them back to the OS. But then it might end up taking more time to bring the app back again and it's not that big of a win. It depends where the delay is for you, really. e.g. are we spending all our time in image decoding or GL setup or disk access .....

**Comment by jsuder** [comment]
Here's a log from a couple of runs on my iMac, which is significantly faster than the MBA. It takes I think a bit over a second less here, but it's still about 5.5s from pressing the icon until the projects appear.

https://gist.github.com/jsuder/2f150adf8fcd5cc65de9

**Comment by mikehearn** [comment]
Thanks. Yes that's a lot slower than what I see. I'm surprised there's such a big difference between MBA, iMac and MacBook Pro. How many cores do those machines have? Perhaps the issue is less parallelism during startup.

**Comment by jsuder** [comment]
iMac: Core i5 2,9 GHz with 4 cores
MBA: Core i5 1,8 GHz with 2 cores (although Lighthouse also reports 4)

I've added a second log from the MBA to the same gist.

BTW, the log on the iMac has 376 MB (compared to 5 MB on the MBA) and it seems to be filled mostly with this:
```
03:31:31 24 PeerSocketHandler.exceptionCaught: [109.235.217.244]:8333 - java.nio.channels.CancelledKeyException
03:31:31 24 ConnectionHandler.writeBytes: Error writing message to connection, closing connection
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:77)
	at org.bitcoinj.net.ConnectionHandler.setWriteOps(ConnectionHandler.java:106)
	at org.bitcoinj.net.ConnectionHandler.writeBytes(ConnectionHandler.java:151)
	at org.bitcoinj.core.PeerSocketHandler.sendMessage(PeerSocketHandler.java:88)
	at org.bitcoinj.core.Peer.ping(Peer.java:1429)
	at org.bitcoinj.core.Peer.ping(Peer.java:1420)
	at org.bitcoinj.core.PeerGroup$11.run(PeerGroup.java:1325)
	at com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:582)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
