### ISSUE TITLE
Using drag&drop to save the project-file closes the dialog and skips the "Need to submit" notification

### ISSUE THREAD

**Issue by lightlist** [vinumeris/lighthouse#167]
**Platform:** Ubuntu

**Problem:** When using the drag&drop feature to copy the project file the dialog closes and the user is not prompted to submit the project to the pledge server operator. We know of a few projects that never went live on the server because the user didn't know about the need to submit (or the email address / link).

**Comment by mikehearn** [comment]
Update pushed
