### ISSUE TITLE
Build fails because updatefx is not found. Following change fixed it. 

### ISSUE THREAD

**Issue by Rangak** [vinumeris/lighthouse#184]
diff --git a/client/pom.xml b/client/pom.xml
index 9d33d2f..671bde1 100644
--- a/client/pom.xml
+++ b/client/pom.xml
@@ -145,7 +145,7 @@
         <dependency>
             <groupId>com.vinumeris</groupId>
             <artifactId>updatefx</artifactId>
-            <version>1.4</version>
+            <version>1.4-SNAPSHOT</version>
         </dependency>
         <dependency>
             <groupId>com.vinumeris</groupId>

**Comment by mikehearn** [comment]
Are you on git master? It's set to 1.5 there and should work. But I only made that change a day or so ago.
