### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by ManfredKarrer** [vinumeris/lighthouse#187]
Hi Mike,
the current master is missing 2 dependencies (for updatefx: 1.4-SNAPSHOT is deployed instead of 1.4).
Not sure which bouncycastle version you use, but I added 1.52 which I use and all compiled with it.

```
<dependency>
            <groupId>com.vinumeris</groupId>
            <artifactId>updatefx</artifactId>
            <version>1.4-SNAPSHOT</version>
        </dependency>

<dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.52</version>
        </dependency>
```

**Comment by mikehearn** [comment]
Both UpdateFX and bitcoinj are on Bouncy Castle/Spongy Castle 1.51. 

I've bumped the UpdateFX dependency to 1.5 .... for some reason I only did this on the lighthouse branch before. It's done on master now.
