### ISSUE TITLE
Synchronize with network progress indicator does not stop running

### ISSUE THREAD

**Issue by ManfredKarrer** [vinumeris/lighthouse#75]

**Comment by mudunuri1234** [comment]
Mike, 

I am trying to run BitcoinJ framework in my local. The screen continue synching with net work forever. 
Also, Send me is disabled all the time. Here is the stack trace. Please let me know if you find any .....

Localhost peer not detected.

02:24:01 20 AbstractBlockChain.addWallet: Wallet/chain height mismatch: -1 vs 332640
02:24:01 20 AbstractBlockChain.addWallet: Hashes: null vs 000000000000000005050188c4b38ab58644e1b69aad22dcc99e819d1deb0bb5
02:24:01 21 PeerGroup$7.run: Starting ...

02:24:02 21 PeerGroup.maybeCheckForLocalhostPeer: Localhost peer not detected.

02:24:02 21 PeerGroup.discoverPeers: Peer discovery took 182msec and returned 126 items
02:24:02 21 PeerGroup$5.go: Waiting 1287 msec before next connect attempt to [174.17.50.190]:8333
02:24:04 21 PeerGroup.connectTo: Attempting connection to [176.212.241.24]:8333     (0 connected, 1 pending, 12 max)
02:24:04 21 PeerGroup.connectTo: Attempting connection to [46.61.75.92]:8333     (0 connected, 2 pending, 12 max)
02:24:04 21 PeerGroup.connectTo: Attempting connection to [194.187.183.229]:8333     (0 connected, 3 pending, 12 max)
02:24:04 21 PeerGroup.connectTo: Attempting connection to [198.105.125.72]:8333     (0 connected, 4 pending, 12 max)
02:24:04 21 PeerGroup.connectTo: Attempting connection to [85.157.182.16]:8333     (0 connected, 5 pending, 12 max)
02:24:04 21 PeerGroup.connectTo: Attempting connection to [67.180.32.175]:8333     (0 connected, 6 pending, 12 max)
02:24:04 21 PeerGroup.connectTo: Attempting connection to [108.22.90.168]:8333     (0 connected, 7 pending, 12 max)
02:24:04 21 PeerGroup.connectTo: Attempting connection to [99.104.136.125]:8333     (0 connected, 8 pending, 12 max)
02:24:04 21 PeerGroup.connectTo: Attempting connection to [80.249.204.176]:8333     (0 connected, 9 pending, 12 max)
02:24:04 21 PeerGroup.connectTo: Attempting connection to [178.7.112.191]:8333     (0 connected, 10 pending, 12 max)
02:24:04 21 PeerGroup.connectTo: Attempting connection to [81.0.70.235]:8333     (0 connected, 11 pending, 12 max)
02:24:04 21 PeerGroup.connectTo: Attempting connection to [174.17.50.190]:8333     (0 connected, 12 pending, 12 max)
02:24:05 22 NioClientManager.handleKey: Failed to connect with exception: java.net.ConnectException: Connection refused: no further information
02:24:05 22 PeerGroup.handlePeerDeath: [176.212.241.24]:8333: Peer died      (0 connected, 11 pending, 12 max)
02:24:05 21 PeerGroup$5.go: Waiting 999 msec before next connect attempt to [71.110.62.213]:8333
02:24:05 22 NioClientManager.handleKey: Failed to connect with exception: java.net.ConnectException: Connection refused: no further information
02:24:05 22 PeerGroup.handlePeerDeath: [67.180.32.175]:8333: Peer died      (0 connected, 10 pending, 12 max)
02:24:05 21 PeerGroup$5.go: Waiting 1500 msec before next connect attempt to [46.239.107.74]:8333
02:24:05 22 NioClientManager.handleKey: Failed to connect with exception: java.net.ConnectException: Connection refused: no further information
02:24:05 22 PeerGroup.handlePeerDeath: [85.157.182.16]:8333: Peer died      (0 connected, 9 pending, 12 max)
02:24:05 21 PeerGroup$5.go: Waiting 2250 msec before next connect attempt to [109.251.62.4]:8333
02:24:05 22 NioClientManager.handleKey: Failed to connect with exception: java.net.ConnectException: Connection refused: no further information
02:24:05 22 PeerGroup.handlePeerDeath: [198.105.125.72]:8333: Peer died      (0 connected, 8 pending, 12 max)
02:24:05 21 PeerGroup$5.go: Waiting 3375 msec before next connect attempt to [50.116.9.6]:8333
02:24:05 22 NioClientManager.handleKey: Failed to connect with exception: java.net.ConnectException: Connection refused: no further information
02:24:05 22 PeerGroup.handlePeerDeath: [194.187.183.229]:8333: Peer died      (0 connected, 7 pending, 12 max)
02:24:05 21 PeerGroup$5.go: Waiting 5062 msec before next connect attempt to [88.198.117.34]:8333
02:24:05 22 NioClientManager.handleKey: Failed to connect with exception: java.net.ConnectException: Connection refused: no further information
02:24:05 22 PeerGroup.handlePeerDeath: [108.22.90.168]:8333: Peer died      (0 connected, 6 pending, 12 max)
02:24:05 21 PeerGroup$5.go: Waiting 7593 msec before next connect attempt to [87.106.2.186]:8333
02:24:05 22 NioClientManager.handleKey: Failed to connect with exception: java.net.ConnectException: Connection refused: no further information
02:24:05 22 PeerGroup.handlePeerDeath: [80.249.204.176]:8333: Peer died      (0 connected, 5 pending, 12 max)
02:24:05 21 PeerGroup$5.go: Waiting 10000 msec before next connect attempt to [72.193.104.209]:8333
