### ISSUE TITLE
Email and message field are visible all pledgers

### ISSUE THREAD

**Issue by ManfredKarrer** [vinumeris/lighthouse#90]
The content of the email and msg fields are currently public (not only visible to project owner).
I think that might have privacy issues and reduce the usefulness (we wanted to use the msg fields for the postal address for sending rewards, but that would leak too much private data - so we would need to have an extra step that we contac the users and they send us the address). 
Also users might to prefer that also email is not visible in public.
Maybe a extra public field (what people want to post in public) might be added as a kind of community feature, but I think the app is not designed as community platform, so that might be not needed.

**Comment by mikehearn** [comment]
For beta, I added a public name field and made the email field private. Name of course is optional, and can also be a pseudonym. Comment field is still public. It's meant for encouragement and other things. Private communication can go via email. A private comments section might be a nice extra feature in future.
