### ISSUE TITLE
Cannot claim funds

### ISSUE THREAD

**Issue by ManfredKarrer** [vinumeris/lighthouse#91]
After stresstesting a project (many pledge/revoke, overpay - revoke) i wanted to claim the 100% funded project but it hangs in the claim pledges screen. when i had my local bitcoin core running it the progress indicator was stopping exactly at 50% without the bitcoin core it goes one step further but does not finish as well.
I will send you the logs by mail.

**Comment by mikehearn** [comment]
I haven't seen this since. If we spot it again, let's reopen.
